### ISSUE TITLE
Why are private repos showing up ?

### ISSUE THREAD

**Issue by scottstensland** [sourcegraph/sourcegraph.com#1]
Even though I have the free public repo only account at sourcegraph.com I am seeing my private repos displayed ...  with no indication that they're private 

Are other people seeing my private repos from their sourcegraph.com  ?

If not please give a UI widget indication as such on your list of repos on my 

            https://sourcegraph.com/

**Comment by dadlerj** [comment]
Hey @scottstensland ! Like I mentioned via our email conversation earlier, this was actually the result of you having authorized private code from GitHub with us in the past (and apparently our plan downgrading functionality didn't work). Your private code will always be treated as private per the permissions you've set on GitHub. 

We'll see if there's a better way to indicate private versus public code in the future.
