### ISSUE TITLE
Fix table CSS styles on Markdown README <tables>

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph.com#111]
Tables in Markdown READMEs are currently unstyled. They should be styled.

E.g.:
![image](https://f.cloud.github.com/assets/1976/2294701/b7435a18-a085-11e3-90cd-3a0d4ccc8bd4.png)
(from https://sourcegraph.com/github.com/sourcegraph/graphkit)

(HT @alexdantas)

**Comment by NickPresta** [comment]
Just pinging for a status update on this issue.

It seems this problem is still around and can be fixed (it seems) by adding `class="table table-bordered"`.

Is there an upstream that does the markdown -> HTML conversion that I can submit a PR against?

**Comment by sqs** [comment]
We use blackfriday, which actually makes it really easy to customize this already, with [(Renderer).Table](https://sourcegraph.com/github.com/russross/blackfriday@master/.GoPackage/github.com/russross/blackfriday/.def/Renderer/Table). I just pushed a fix. It should be live in about 10-15 min. Sorry for the slow turnaround time on this!

**Comment by NickPresta** [comment]
No problem. Thanks for the quick followup.
