### ISSUE TITLE
Make the code file color theme configurable

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph.com#143]
Some people don't like the dark theme, and @jbenet uses Nocturne, which it messes up.

![image](https://cloud.githubusercontent.com/assets/1976/3504909/6a043cae-0651-11e4-8afd-cdb50f60753c.png)

**Comment by sqs** [comment]
The color scheme is now dark on light throughout the site, by popular request. If anyone wants the old scheme back, let us know...we might add a theme chooser later.

![image](https://cloud.githubusercontent.com/assets/1976/5712777/25efc274-9a6a-11e4-9a56-a69f8840e65f.png)

**Comment by jbenet** [comment]
![](http://www.drodd.com/images10/clapping-gif24.gif)
