### ISSUE TITLE
Go Gondola web framework fails

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph.com#312]
I noticed the github.com/rainycape/gondola build is failing for a variety of reasons (see https://sourcegraph.com/github.com/rainycape/gondola/.builds/910480 for example):

* [ ] we haven't set it to use its custom import path gnd.la
* [ ] even if we set it to use that, sourcegraph.com/gnd.la would be interpreted as a user lookup for gnd.la (based on our URL structure so far)
* [ ] it hits the GitHub rate limit of 60 per minute doing dep lookups

**Comment by neelance** [comment]
Building this repository works now.
