### ISSUE TITLE
PR commenting

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph.com#318]
Or, maybe in the interim, "view this file on GitHub" link so I can at least jump to where I'd want to add the comment on GitHub.

**Comment by neelance** [comment]
I just tried if this works, but I'm getting `error: could not save comment`. :-(

**Comment by beyang** [comment]
Thanks for filing. This is lower priority and will likely change given other changes to the product we're working on, so I'm going to close this.

**Comment by neelance** [comment]
For clarification: Is this about commenting on files of a PR or commenting in general, e.g. https://sourcegraph.com/github.com/gopherjs/gopherjs/.pulls/226 ? Because the "Write a comment" box on this page does not work for me.
