### ISSUE TITLE
Failed build tasks should be retried

### ISSUE THREAD

**Issue by samertm** [sourcegraph/sourcegraph.com#359]
For large builds, a couple of tasks will usually fail with EOF errors. These should be retried before they are marked as failed.

**Comment by sqs** [comment]
It should retry these a few times if they look like docker json stdout
errors. Also I had thought this was fixed in Docker 1.4...have you seen it
recently? You just saw it? https://github.com/docker/docker/issues/3631

**Comment by samertm** [comment]
I just saw this running locally, let me see if I can find an example from
the site.

**Comment by samertm** [comment]
Yeah, it seems like phantom EOFs are no longer an issue. Sorry for the noise!
