### ISSUE TITLE
Can't ask a project maintainer to set up a webhook

### ISSUE THREAD

**Issue by femtotrader** [sourcegraph/sourcegraph.com#361]
Hello,

https://sourcegraph.com/github.com/Infinidat/munch
when I click on "Ask the owner to enable it." I get

https://github.com/Infinidat/munch/issues/new?body=I+want+to+use+%5BSourcegraph+code+search+and+code+review%5D%28https%3A%2F%2Fsourcegraph.com%29+with+munch.+A+project+maintainer+needs+to+enable+it+to+set+up+a+webhook+so+the+code+is+up-to-date+there.%0A%0ACould+you+please+enable+munch+on+%40Sourcegraph+by+going+to+https%3A%2F%2Fsourcegraph.com%2Fgithub.com%2FInfinidat%2Fmunch+and+clicking+on+Settings%3F+%28It+should+only+take+15+seconds.%29%0A%0AThank+you%21&title=Enable+Sourcegraph

But it returns an error page.

Kind regards

**Comment by sqs** [comment]
This occurs because the admin of the GitHub repository has disabled GitHub issues. There's no way for us to detect that ahead of time using the current method. You'll need to email him/her or otherwise find a way to contact him/her to ask.
