### ISSUE TITLE
Blog empty/not accessible?

### ISSUE THREAD

**Issue by shurcooL** [sourcegraph/sourcegraph.com#362]
Is it normal that the Sourcgraph blog appears to be empty, and links to previous blog posts are giving 404?

https://sourcegraph.com/blog

![image](https://cloud.githubusercontent.com/assets/1924134/5990155/a82abee0-a958-11e4-980d-0156197566b7.png)

**Comment by sqs** [comment]
Whoops, nope, will fix soon. Thanks for reporting. Need monitoring on this too.

**Comment by shurcooL** [comment]
> Thanks for reporting.

No problem, and thanks!

**Comment by beyang** [comment]
Thanks again for reporting this Dmitri. Blog is back up now :)

—

Beyang Liu

✱beyang <https://sourcegraph.com/beyang> | @beyang
<https://twitter.com/beyang> | +1 714 362 6538

✱Sourcegraph <https://sourcegraph.com/> | Connecting people and code |
@srcgraph <https://twitter.com/srcgraph>
