### ISSUE TITLE
no way to access examples page from UI

### ISSUE THREAD

**Issue by samertm** [sourcegraph/sourcegraph.com#368]
The examples page for a definition is accessable by appending "/.examples" to a def's url, but there's no way to access it from the UI.

**Comment by gbbr** [comment]
This was intentional. Do you reckon that page would be useful? I could find
a place for a link

**Comment by samertm** [comment]
Ah, I didn't realize that. I find the examples list helpful when I need to look through more than a couple references, and I think just having a button to it would be fine.

**Comment by beyang** [comment]
I find the examples page useful too

**Comment by gbbr** [comment]
I've added it back in that case, by popular demand :)

![screen shot 2015-02-21 at 12 10 38 pm](https://cloud.githubusercontent.com/assets/6686356/6313170/d1bec424-b9c3-11e4-9391-dd9e2d040ca2.png)

It'll temporarily look like this until I submit my PR with the code view in the examples, are you guys happy with this?

(do not close issue because I need to consider this in my PR)

**Comment by sqs** [comment]
Great for now!

**Comment by samertm** [comment]
I just got feedback that the button is nonobvious if you don't know that it means "list all examples". Can we make the function of the button more obvious in the next PR? @gbbr Reopening for now.

**Comment by gbbr** [comment]
@samertm My idea was to display a text that explains what the button does when it is hovered (ie. "Open examples in new window") but leave it in the same position - what do you think? I think anything more might be a distraction, but I'm open to discussions / suggestions on this.

**Comment by samertm** [comment]
I think, from the perspective of a first-time user, the button looks like a "navigate to" link and it's placed on top of an example, which may give the impression that the button navigates to that specific example, rather than to *all* of the examples. Use your own discretion, though.
