### ISSUE TITLE
There should be a way to select ranges from the UI

### ISSUE THREAD

**Issue by samertm** [sourcegraph/sourcegraph.com#370]
cc @kunalpowar

**Comment by samertm** [comment]
Also, sourceboxes no longer embed selected lines.

**Comment by gbbr** [comment]
This takes around 1-2 hours to implement. I can add it in the next PR with
the clean-up and tests (which will be done by the end of the week), or if
it's more urgent than that - I could just add it into master. Let me know
which option you'd like.

**Comment by gbbr** [comment]
This is now available in the UI.
