### ISSUE TITLE
How come Microsoft uses sourcegraph as in your picture in frontpage if you don't support C#?

### ISSUE THREAD

**Issue by 0d85391d7c2e** [sourcegraph/sourcegraph.com#376]
I'm kinda confused.

**Comment by beyang** [comment]
There are Microsoft programmers using Sourcegraph on open-source projects that aren't written in C#. That having been said, C# is high on our priority list of languages to support (https://github.com/sourcegraph/srclib-csharp). If you'd like to help contribute to srclib-csharp, let us know!
