### ISSUE TITLE
Build 2133335 Failed

### ISSUE THREAD

**Issue by vladimir-ch** [sourcegraph/sourcegraph.com#377]
The [builds](https://sourcegraph.com/github.com/gonum/optimize/.builds) of [gonum/optimize](https://sourcegraph.com/github.com/gonum/optimize) project fail, the logs say something about `Cannot start container` and `cannot allocate memory`.

**Comment by beyang** [comment]
Thanks for reporting this. We're looking into it and hope to have it up soon.

**Comment by beyang** [comment]
Looks like it completed successfully: https://sourcegraph.com/github.com/gonum/optimize. Sorry about the issue and let us know if you have any other feedback on Sourcegraph!

**Comment by vladimir-ch** [comment]
Thanks for resolving this so quickly!

**Comment by beyang** [comment]
Absolutely :) Let us know if there's anything else that comes up, and if you like the product, please share it with others!
