### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by vladimir-ch** [sourcegraph/sourcegraph.com#379]
After clicking on Sign in button, I get the following error:

Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.

**Comment by beyang** [comment]
Does this continue to happen? We've not seen this for any other user accounts.

**Comment by vladimir-ch** [comment]
I didn't test again and can't test it until Wednesday. I guess it was some
kind of glitch on my side, you can close this.

**Comment by beyang** [comment]
let us know if it reappears!
