### ISSUE TITLE
build 2158700 because docker failed to start

### ISSUE THREAD

**Issue by kjk** [sourcegraph/sourcegraph.com#380]
Looks like internal problem where the build docker image failed to start due to insufficient computing resources.

Full log: https://sourcegraph.com/github.com/sumatrapdfreader/sumatrapdf/.builds/2158700/log

**Comment by beyang** [comment]
Sorry about this. Builds are up and running again, and it's processed now: https://sourcegraph.com/github.com/sumatrapdfreader/sumatrapdf
