### ISSUE TITLE
Sourcegraph email setting showing someone else's email

### ISSUE THREAD

**Issue by facelessuser** [sourcegraph/sourcegraph.com#392]
In Sourcegraph's settings under email, it is showing someone else's email along side mine.  I find this troubling.  Sourcegraph seems to read my email's from github, but there is this other email that won't go away.

**Comment by sqs** [comment]
I'm sorry for the bug. I will look into why this occurred. In the meantime, I deleted the erroneous email. Thank you for reporting this.

**Comment by facelessuser** [comment]
Thanks!
