### ISSUE TITLE
Build failure in github.com/geoffreywiseman/Moo

### ISSUE THREAD

**Issue by geoffreywiseman** [sourcegraph/sourcegraph.com#397]
This looks like a permissions error on source graph, rather than something with my project? Or am I misreading the build log?
https://sourcegraph.com/github.com/geoffreywiseman/Moo

**Comment by beyang** [comment]
Yep, it looks like an issue with one of the worker nodes. I restarted the build via the "rebuild" button and it looks like it just succeeded: https://sourcegraph.com/github.com/geoffreywiseman/Moo
