### ISSUE TITLE
Sourcebox CSS isn't namespaced

### ISSUE THREAD

**Issue by mholt** [sourcegraph/sourcegraph.com#406]
When I embed Sourcegraph snippets in a blog that I'm designing, the sourcebox.css styles are affecting the rest of my page, for example:

<img width="298" alt="screen shot 2015-07-20 at 11 43 43 am" src="https://cloud.githubusercontent.com/assets/1128849/8782731/a3c396e0-2ed4-11e5-9495-230b3e5e53b9.png">

It would be nice if they were 'namespaced' like `.sourcebox .button` or something like that.

**Comment by beyang** [comment]
Thanks for filing this -- in the midst of a product push right now, but hope to fix this soon!
