### ISSUE TITLE
Embed code refers to internal address

### ISSUE THREAD

**Issue by alexsaveliev** [sourcegraph/sourcegraph.com#408]
Links in embed code and JSON request at https://beta.sourcegraph.com/github.com/aws/aws-sdk-java@59a3b3717ca08d6084c148fc318708f0f57234ec/.tree/aws-java-sdk-ecs/src/main/java/com/amazonaws/services/ecs/AmazonECSClient.java/.share refer to https://sourcegraph.com while while they should refer to the site I'm currently on - https://beta.sourcegraph.com

When I'm running local copy of `src` using the following command
```
src -v --grpc-endpoint http://localhost:3100 --http-endpoint http://localhost:3000/api/ serve --http-addr=:3000 --grpc-addr=:3100
```
and with the port forwarding defined as PUBLIC-NAME:PUBLIC-PORT => INTERNAL-NAME:3000, then embed code and JSON request refer to `http://INTERNAL-NAME:3000` while they should refer to `http://PUBLIC-NAME:PUBLIC-PORT` (this also makes preview impossible)

**Comment by sqs** [comment]
For (1), dndeed - that is because it was switched over to https://sourcegraph.com. We need to remove the beta.sourcegraph.com DNS alias. Access it at https://sourcegraph.com going forward.

For (2), use `src serve [other options] --app-url=https://public-name:public-port` to set the external URL.
