### ISSUE TITLE
Why does Sourcegraph need write access to public and private repos on github?

### ISSUE THREAD

**Issue by frol** [sourcegraph/sourcegraph.com#418]
Once I try to connect my Github account to Sourcegraph, I see that it requires quite questionable list of permissions:

* read and **write** access to my profile;
* read and **write** access to public and **private** repos.

Is it really required?

**Comment by sqs** [comment]
Unfortunately GitHub does not allow fine-grained access scopes, such as read-only repository access. Sourcegraph doesn't write to your profile or repositories, and we hope to be able to narrow the scopes in the future if GitHub allows it. (With that said, I think we can eliminate the requirement for profile write access—we are looking into that now.)

If you just want to try Sourcegraph on public repositories, you don't need to log in. Just go to, e.g., https://sourcegraph.com/github.com/gorilla/mux. 

You can also run Sourcegraph locally and inspect the source code if you'd like: https://src.sourcegraph.com/sourcegraph.

**Comment by frol** [comment]
Wow, the tip about public repos is super helpful!

Yeah, I have reviewed GitHub scopes and true, they are very limited...

Thank you!
