### ISSUE TITLE
Firefox extension doesn't work.

### ISSUE THREAD

**Issue by madper** [sourcegraph/sourcegraph.com#419]
Hi folks!
Today I installed the sourcegraph extension for firefox but found it doesn't work. (I tested both java and golang repo)
In the meanwhile I tested the chrome version which works well.

My firefox is firefox 50.0-stable. The extension is installed from https://addons.mozilla.org/en_US/firefox/addon/sourcegraph-addon-for-github/

I tried to remove other github related extension. But didn't fix the issue.

**Comment by lindaxie** [comment]
@madper thanks for flagging this. We made some big improvements to the code intelligence backend that unfortunately broke the current version of our FireFox extension (1.1.27). 

We just submitted a new version of the extension last week, it's currently being reviewed by the Firefox store and should be available in a few days!

**Comment by madper** [comment]
@lindaxie I see. Thanks for the reply.
