### ISSUE TITLE
Main page says "Support for Go, TypeScript, and C" but docs#languages_supported says only "Go"

### ISSUE THREAD

**Issue by FlashSheridan** [sourcegraph/sourcegraph.com#421]
https://sourcegraph.com/ says (if you haven't logged in): "Support for Go, TypeScript, and C" but https://sourcegraph.com/docs#languages_supported says only "Go", followed by “In Beta: • TypeScript  • JavaScript  • C".  So a new user drilling down loses non-Beta support for TypeScript and C, but gains Beta support for JavaScript.

![main page screen shot 2016-12-09 at 7 55 59 pm](https://cloud.githubusercontent.com/assets/758199/21071091/d19b8f9e-be4a-11e6-8dfd-51e53ac7d772.png)
![docs screen shot 2016-12-09 at 7 57 14 pm](https://cloud.githubusercontent.com/assets/758199/21071092/d93514e6-be4a-11e6-9fad-0dd6842eefc1.png)

**Comment by mejamiewilson** [comment]
Thanks Flash, moving this issue to our internal tracker.
