### ISSUE TITLE
Clicking on a local variable in wget connect.c jumps to unrelated union member in mswindows.c

### ISSUE THREAD

**Issue by FlashSheridan** [sourcegraph/sourcegraph.com#422]
Clicking on the local variable `sin` at the beginning of line 93 in [wget connect.c](https://sourcegraph.com/github.com/mirror/wget/-/blob/src/connect.c#L93) should jump to its definition at line 89.  Instead it  jumps to an unrelated union member of the same name in the function `inet_ntop` in [mswindows.c](https://sourcegraph.com/github.com/mirror/wget/-/blob/src/mswindows.c#L586:24).

_Configuration:_ Chrome 55.0.2883.87 on MacOS 10.9.5, no plugin installed. Similar results on a messy MacOS 10.11.6 machine with Chrome 55.0.2883.75 and the Sourcegraph plugin installed, and with Safari 9.1.3 (11601.7.8).

_Before Clicking:_

![before click screen shot 2016-12-09 at 8 17 14 pm](https://cloud.githubusercontent.com/assets/758199/21071219/71ba5372-be4e-11e6-90c0-e445b9aea7db.png)

_After Clicking:_

![after click screen shot 2016-12-09 at 8 18 09 pm](https://cloud.githubusercontent.com/assets/758199/21071222/827636ae-be4e-11e6-8071-a5ada6e86ae3.png)

**Comment by mejamiewilson** [comment]
Thanks Flash, moving this issue to our internal tracker.
