### ISSUE TITLE
“Click on a symbol to jump to its definition” sometimes highlights its occurrences instead

### ISSUE THREAD

**Issue by FlashSheridan** [sourcegraph/sourcegraph.com#423]
https://sourcegraph.com/docs#go_to_definition says, “Click on a symbol to jump to its definition,” but sometimes Sourcegraph highlights its occurrences instead.  
Clicking on the occurrence of the parameter `downloaded_set` in line 78 of [wget convert.c](https://sourcegraph.com/github.com/mirror/wget/-/blob/src/convert.c#L78) instead highlights its occurrences, but does not reveal the parameter definition at line 63.  It's necessary to scroll up to see the definition.

_Initial Click:_

![initial click screen shot 2016-12-09 at 8 11 42 pm](https://cloud.githubusercontent.com/assets/758199/21071296/5d3b0a24-be51-11e6-9f4f-e6e8551ce09e.png)

_After Scrolling Up:_
![scrolled up screen shot 2016-12-09 at 8 12 00 pm](https://cloud.githubusercontent.com/assets/758199/21071297/65c51bda-be51-11e6-871d-193b8d33546a.png)

**Comment by mejamiewilson** [comment]
Thanks Flash, moving this issue to our internal tracker.
