### ISSUE TITLE
Peek Definition should list file names for multiple definitions

### ISSUE THREAD

**Issue by FlashSheridan** [sourcegraph/sourcegraph.com#424]
When right-clicking on the local variable `url` in [wget convert.c#L95](https://sourcegraph.com/github.com/mirror/wget/-/blob/src/convert.c#L95), Sourcegraph shows five possibilities.  These possibilities are headed by the same repeated text, “wget mirror”.  I would instead recommend listing the file names in which the definitions occur, which would make selecting the appropriate one much easier.  (That none of them is the actual definition at line 88 of the current file is a separate bug, presumably #422.)  

_Before Clicking:_

![before clicking screen shot 2016-12-09 at 9 03 51 pm](https://cloud.githubusercontent.com/assets/758199/21071432/e28c2f98-be54-11e6-9c86-2fa07b7e42b7.png)

_In convert.h_

![in convert h screen shot 2016-12-09 at 9 04 48 pm](https://cloud.githubusercontent.com/assets/758199/21071439/f71d1e40-be54-11e6-84da-8a8ae4431092.png)

_In url.h_
![in url h screen shot 2016-12-09 at 9 05 51 pm](https://cloud.githubusercontent.com/assets/758199/21071441/004345ee-be55-11e6-8a5b-1af4d92309b4.png)

**Comment by mejamiewilson** [comment]
Thanks Flash, moving this issue to our internal tracker.
