### ISSUE TITLE
Docs page's opening “Sourcegraph is a tool” doesn't distinguish the plugin from hosted web pages

### ISSUE THREAD

**Issue by FlashSheridan** [sourcegraph/sourcegraph.com#425]
The opening text on https://sourcegraph.com/docs, “Sourcegraph is a tool…”, should better distinguish the sourcegraph.com-hosted web pages from the Chrome plugin, and document compatibility for each separately.  In particular, there is no mention anywhere on the docs page that Sourcegraph can be used in an arbitrary browser without the plugin by viewing github.com pages through https://sourcegraph.com/github.com.  (It didn't take me long to figure this out, but a less-motivated user might not have gotten that far.)

The table of contents implies that the “Languages Supported” list applies to both the plugin and the web pages, but after reading the plugin section, it's easy to assume that it applies only to the plugin, especially as there is no mention of browser compatibility.  (My limited experience suggests that the hosted web pages work equally well in Chrome and Safari for C files, but the Extension does not work for me for C in Chrome, and of course has no effect in Safari.)

**Comment by mejamiewilson** [comment]
Thanks Flash, moving this issue to our internal tracker.
