### ISSUE TITLE
Autofocus for search field

### ISSUE THREAD

**Issue by corpix** [sourcegraph/sourcegraph.com#7]
I think search field should focus when user has start to type. It's a good practice used by google, bing etc

**Comment by neelance** [comment]
I think this can be closed. The hotkey `/` key seems to work. Search bar is not autofocused any more, but in my opinion that's okay since the landing page has so much more to offer and having to select the search box makes the helpful `Type ? for help` popup appear.

**Comment by corpix** [comment]
Thats ok. Thank you!
